name: Push README
on:
    push:
      branches: [ "master" ]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'README.md'
        destination_repo: 'solafide-dev/solafide-dev.github.io'
        destination_folder: 'content/en/docs/Libraries/august'
        user_email: 'cameronchunn@gmail.com'
        user_name: 'applehat'
        commit_message: 'Update README.md from august repo'
